### ISSUE TITLE
saving without setting a value causes a crash

### ISSUE THREAD

**Issue by rojer** [mongoose-os-libs/bt-service-config#1]
@pwiner99 on gitter:

Possible bug/issue with bt -service-config. If, over BLE, I set a valid "key". And I don't set a "value". And then try to "save" = 1. Then the program will crash dump: Guru Meditation Error: Core 0 panic'ed (LoadProhibited).

**Comment by nliviu** [comment]
Crash dump in [esp32_bt_svc_config.c line 176](https://github.com/mongoose-os-libs/bt-service-config/blob/d6e6624f05d647ccc04ded1d62f1ee218886b360/src/esp32/esp32_bt_svc_config.c#L176) when setting a null string value, `*svp` is NULL.

Fix: `LOG(LL_INFO, ("'%.*s' = '%s'", (int) sd->key.len, sd->key.buf,
                    (NULL != *svp ? *svp : "null")));`

**Comment by rojer** [comment]
thanks @nliviu ! sent a fix

**Comment by cpq** [comment]
LG
