### ISSUE TITLE
recipe for target 'mgos_bt_svc_config.o' failed

### ISSUE THREAD

**Issue by Praveena0989** [mongoose-os-libs/bt-service-config#2]
This was working till yesterday but suddenly started crashing.

/deps/bt-service-config/src/mgos_bt_svc_config.c:34:27: fatal error: mgos_bt_gatts.h: No such file or directory
compilation terminated.
/mongoose-os/fw/platforms/esp32/src/esp32_src.mk:113: recipe for target 'mgos_bt_svc_config.o' failed
make[1]: *** [mgos_bt_svc_config.o] Error 1

**Comment by rojer** [comment]
make sure bt-comon lib is up to date. wipe entire deps folder if needed.
